# Info
info=1                      	# 0 = no info at boot, 1 = display info at boot

# Playlist
playlist=RpiTeaM eLLuiGi.txt         	# Plays the playlist specified in /playlist
random=1                    	# 0 = play in order, 1 = play randomly

# Wi-Fi & Bluetooth
wifi_enabled=1             	# 0 = Wi-Fi disabled, 1 = Wi-Fi enabled (keep at 1)
wifi_ssid=                 	# Your Wi-Fi network name
wifi_password=             	# Your Wi-Fi password
bluetooth_enabled=0        	# 0 = Bluetooth disabled, 1 = Bluetooth enabled (keep at 0)
                            	# Enable if you experience interference (e.g. 8Bitdo Pro 3 controller)
bluetooth_name=ESP32-GIF    	# Bluetooth name

wifi_static_enabled=1       	# 0 = DHCP, 1 = static IP (recommended)
wifi_static_ip=xxx.xxx.x.xx   	# Only if wifi_static_enabled=1
wifi_gateway=192.168.0.254      # Only if wifi_static_enabled=1
wifi_subnet=255.255.255.0       # Only if wifi_static_enabled=1
wifi_dns1=1.1.1.1               # Only if wifi_static_enabled=1
wifi_dns2=8.8.8.8               # Only if wifi_static_enabled=1

# MQTT
recalbox_ip=xxx.xxx.x.xx  	# Fixed IP address of your Recalbox
