THEME = {
    "name": "Game Boy",
    "author": "Shan_ayA",
    "version": "1.0",
    "colors": {
        "bg_main": "#8BAC0F",
        "bg_frame": "#9CBD1A",
        "fg_text": "#FFFFFF",
        "fg_text_light": "#D4E680",
        "fg_heading": "#306230",
        "bg_button_start": "#306230",
        "fg_button_start": "#FFFFFF",
        "bg_button_danger": "#0D4F0D",
        "bg_button_action": "#9CBD1A",
        "bg_button_normal": "#7A9A0A",
        "bg_listbox": "#6B8A08",
        "fg_listbox": "#FFFFFF",
        "bg_text": "#5A7A06",
        "fg_textbox": "#E0E0C0",
        "bg_tab": "#8BAC0F",
        "bg_tab_selected": "#9CBD1A",
        "bg_progress": "#6B8A08",
        "fg_progress": "#306230",
        "bg_silk": "transparent",
        "fg_silk": "#5A7A06",
        "bg_notebook": "#8BAC0F",
    },
    "fonts": {"default_size": 10},
}
