THEME = {
    "name": "Neogeo",
    "author": "RecalBoxDMD",
    "version": "1.0",
    "colors": {
        "bg_main": "#282828",
        "bg_frame": "#393939",
        "fg_text": "#FFFFFF",
        "fg_text_light": "#AAAAAA",
        "fg_heading": "#CEB96E",
        "bg_button_start": "#CEB96E",
        "fg_button_start": "#FFFFFF",
        "bg_button_danger": "#8B0000",
        "bg_button_action": "#282828",
        "bg_button_normal": "#414141",
        "bg_listbox": "#242424",
        "fg_listbox": "#FFFFFF",
        "bg_text": "#242424",
        "fg_textbox": "#E0E0E0",
        "bg_tab": "#282828",
        "bg_tab_selected": "#3D3D3D",
        "bg_progress": "#202020",
        "fg_progress": "#CEB96E",
        "bg_silk": "transparent",
        "fg_silk": "#141414",
        "bg_notebook": "#282828",
    },
    "fonts": {"default_size": 10},
}
