THEME = {
    "name": "Super Nintendo (SNES)",
    "author": "Shan_ayA",
    "version": "1.0",
    "colors": {
        "bg_main": "#3B3B4D",
        "bg_frame": "#4A4A5E",
        "fg_text": "#FFFFFF",
        "fg_text_light": "#BBBBCC",
        "fg_heading": "#FFD700",
        "bg_button_start": "#8B5CF6",
        "fg_button_start": "#FFFFFF",
        "bg_button_danger": "#DC2626",
        "bg_button_action": "#FFD700",
        "bg_button_normal": "#6B6B7D",
        "bg_listbox": "#2A2A3D",
        "fg_listbox": "#FFFFFF",
        "bg_text": "#1E1E2E",
        "fg_textbox": "#E0E0E0",
        "bg_tab": "#3B3B4D",
        "bg_tab_selected": "#4A4A5E",
        "bg_progress": "#2A2A3D",
        "fg_progress": "#8B5CF6",
        "bg_silk": "transparent",
        "fg_silk": "#9999BB",
        "bg_notebook": "#3B3B4D",
    },
    "fonts": {"default_size": 10},
}
