THEME = {
    "name": "SEGA Mega Drive",
    "author": "Shan_ayA",
    "version": "1.0",
    "colors": {
        "bg_main": "#1A1A2E",
        "bg_frame": "#252540",
        "fg_text": "#FFFFFF",
        "fg_text_light": "#8888AA",
        "fg_heading": "#4FC3F7",
        "bg_button_start": "#4FC3F7",
        "fg_button_start": "#000000",
        "bg_button_danger": "#E53935",
        "bg_button_action": "#FF9800",
        "bg_button_normal": "#2E2E4A",
        "bg_listbox": "#12121E",
        "fg_listbox": "#FFFFFF",
        "bg_text": "#0D0D18",
        "fg_textbox": "#CCCCDD",
        "bg_tab": "#1A1A2E",
        "bg_tab_selected": "#252540",
        "bg_progress": "#12121E",
        "fg_progress": "#4FC3F7",
        "bg_silk": "transparent",
        "fg_silk": "#6666AA",
        "bg_notebook": "#1A1A2E",
    },
    "fonts": {"default_size": 10},
}
