THEME = {
    "name": "Dreamcast",
    "author": "RecalBoxDMD",
    "version": "1.0",
    "colors": {
        "bg_main": "#D8D8D8",
        "bg_frame": "#DBDBDB",
        "fg_text": "#000000",
        "fg_text_light": "#555555",
        "fg_heading": "#ED7D6B",
        "bg_button_start": "#ED7D6B",
        "fg_button_start": "#000000",
        "bg_button_danger": "#8B0000",
        "bg_button_action": "#D8D8D8",
        "bg_button_normal": "#DCDCDC",
        "bg_listbox": "#C2C2C2",
        "fg_listbox": "#000000",
        "bg_text": "#FFFFFF",
        "fg_textbox": "#000000",
        "bg_tab": "#D8D8D8",
        "bg_tab_selected": "#DBDBDB",
        "bg_progress": "#ACACAC",
        "fg_progress": "#ED7D6B",
        "bg_silk": "#F3F3F3",
        "fg_silk": "#000000",
        "bg_notebook": "#D8D8D8",
    },
    "fonts": {"default_size": 10},
}
