THEME = {
    "name": "Default",
    "author": "RecalBoxDMD",
    "version": "1.0",
    "colors": {
        "bg_main": "#F8F8F8",
        "bg_frame": "#F8F8F8",
        "fg_text": "#000000",
        "fg_text_light": "#555555",
        "fg_heading": "#FFFFBA",
        "bg_button_start": "#FFFFBA",
        "fg_button_start": "#000000",
        "bg_button_danger": "#8B0000",
        "bg_button_action": "#F8F8F8",
        "bg_button_normal": "#F8F8F8",
        "bg_listbox": "#DFDFDF",
        "fg_listbox": "#000000",
        "bg_text": "#FFFFFF",
        "fg_textbox": "#000000",
        "bg_tab": "#F8F8F8",
        "bg_tab_selected": "#F8F8F8",
        "bg_progress": "#C6C6C6",
        "fg_progress": "#FFFFBA",
        "bg_silk": "#F3F3F3",
        "fg_silk": "#000000",
        "bg_notebook": "#F8F8F8",
    },
    "fonts": {"default_size": 10},
}
