THEME = {
    "name": "default",
    "author": "RecalBoxDMD",
    "version": "1.0",
    "colors": {
        "bg_main": "#F3F3F3",
        "bg_frame": "#FFFFFF",
        "fg_text": "#000000",
        "fg_text_light": "#555555",
        "fg_heading": "#000000",
        "bg_button_start": "#00D084",
        "fg_button_start": "#000000",
        "bg_button_danger": "#FF5C5C",
        "bg_button_action": "#FFD400",
        "bg_button_normal": "#FFFFFF",
        "bg_listbox": "#FFFFFF",
        "fg_listbox": "#000000",
        "bg_text": "#FFFFFF",
        "fg_textbox": "#000000",
        "bg_tab": "#F0F0F0",
        "bg_tab_selected": "#FFFFFF",
        "bg_progress": "#E0E0E0",
        "fg_progress": "#00D084",
        "bg_silk": "#F3F3F3",
        "fg_silk": "#000000",
        "bg_notebook": "#F3F3F3",
    },
    "fonts": {"default_size": 10},
}
