THEME = {
    "name": "Dreamcast",
    "author": "Shan_ayA",
    "version": "1.0",
    "colors": {
        "bg_main": "#FFFFFF",
        "bg_frame": "#F0F0F0",
        "fg_text": "#000000",
        "fg_text_light": "#666666",
        "fg_heading": "#FF6F00",
        "bg_button_start": "#FF6F00",
        "fg_button_start": "#FFFFFF",
        "bg_button_danger": "#D32F2F",
        "bg_button_action": "#1565C0",
        "bg_button_normal": "#E8E8E8",
        "bg_listbox": "#FFFFFF",
        "fg_listbox": "#000000",
        "bg_text": "#F5F5F5",
        "fg_textbox": "#000000",
        "bg_tab": "#FFFFFF",
        "bg_tab_selected": "#F0F0F0",
        "bg_progress": "#E0E0E0",
        "fg_progress": "#FF6F00",
        "bg_silk": "transparent",
        "fg_silk": "#AAAAAA",
        "bg_notebook": "#FFFFFF",
    },
    "fonts": {"default_size": 10},
}
