THEME = {
    "name": "Nintendo 64",
    "author": "Shan_ayA",
    "version": "1.0",
    "colors": {
        "bg_main": "#1B3A1B",
        "bg_frame": "#264D26",
        "fg_text": "#FFFFFF",
        "fg_text_light": "#88AA88",
        "fg_heading": "#FFD700",
        "bg_button_start": "#66BB6A",
        "fg_button_start": "#FFFFFF",
        "bg_button_danger": "#C62828",
        "bg_button_action": "#FFD700",
        "bg_button_normal": "#2D5E2D",
        "bg_listbox": "#0F260F",
        "fg_listbox": "#FFFFFF",
        "bg_text": "#0A1A0A",
        "fg_textbox": "#CCDDCC",
        "bg_tab": "#1B3A1B",
        "bg_tab_selected": "#264D26",
        "bg_progress": "#0F260F",
        "fg_progress": "#66BB6A",
        "bg_silk": "transparent",
        "fg_silk": "#557755",
        "bg_notebook": "#1B3A1B",
    },
    "fonts": {"default_size": 10},
}
