THEME = {
    "name": "PlayStation",
    "author": "Shan_ayA",
    "version": "1.0",
    "colors": {
        "bg_main": "#C0C0C0",
        "bg_frame": "#D4D4D4",
        "fg_text": "#000000",
        "fg_text_light": "#555555",
        "fg_heading": "#000000",
        "bg_button_start": "#2196F3",
        "fg_button_start": "#FFFFFF",
        "bg_button_danger": "#E53935",
        "bg_button_action": "#FFB300",
        "bg_button_normal": "#E8E8E8",
        "bg_listbox": "#FFFFFF",
        "fg_listbox": "#000000",
        "bg_text": "#F0F0F0",
        "fg_textbox": "#000000",
        "bg_tab": "#C0C0C0",
        "bg_tab_selected": "#D4D4D4",
        "bg_progress": "#E0E0E0",
        "fg_progress": "#2196F3",
        "bg_silk": "transparent",
        "fg_silk": "#777777",
        "bg_notebook": "#C0C0C0",
    },
    "fonts": {"default_size": 10},
}
