THEME = {
    "name": "Playstation",
    "author": "RecalBoxDMD",
    "version": "1.0",
    "colors": {
        "bg_main": "#A8A8A8",
        "bg_frame": "#AEAEAE",
        "fg_text": "#000000",
        "fg_text_light": "#555555",
        "fg_heading": "#FFD62E",
        "bg_button_start": "#FFD62E",
        "fg_button_start": "#000000",
        "bg_button_danger": "#8B0000",
        "bg_button_action": "#A8A8A8",
        "bg_button_normal": "#B2B2B2",
        "bg_listbox": "#979797",
        "fg_listbox": "#000000",
        "bg_text": "#FFFFFF",
        "fg_textbox": "#000000",
        "bg_tab": "#A8A8A8",
        "bg_tab_selected": "#B0B0B0",
        "bg_progress": "#868686",
        "fg_progress": "#FFD62E",
        "bg_silk": "#F3F3F3",
        "fg_silk": "#000000",
        "bg_notebook": "#A8A8A8",
    },
    "fonts": {"default_size": 10},
}
