THEME = {
    "name": "NEO•GEO AES",
    "author": "Shan_ayA",
    "version": "1.0",
    "colors": {
        "bg_main": "#0D0D0D",
        "bg_frame": "#1A1A1A",
        "fg_text": "#FFFFFF",
        "fg_text_light": "#666666",
        "fg_heading": "#FFD700",
        "bg_button_start": "#E53935",
        "fg_button_start": "#FFFFFF",
        "bg_button_danger": "#B71C1C",
        "bg_button_action": "#FFD700",
        "bg_button_normal": "#222222",
        "bg_listbox": "#000000",
        "fg_listbox": "#FFFFFF",
        "bg_text": "#0A0A0A",
        "fg_textbox": "#CCCCCC",
        "bg_tab": "#0D0D0D",
        "bg_tab_selected": "#1A1A1A",
        "bg_progress": "#111111",
        "fg_progress": "#E53935",
        "bg_silk": "transparent",
        "fg_silk": "#444444",
        "bg_notebook": "#0D0D0D",
    },
    "fonts": {"default_size": 10},
}
